# Generated by Django 3.0.4 on 2020-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polling',
            name='vote1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='polling',
            name='vote2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='polling',
            name='vote3',
            field=models.IntegerField(default='0'),
        ),
    ]
