# Generated by Django 3.0.4 on 2020-03-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200320_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polling',
            new_name='Pollingoption',
        ),
    ]
