# Generated by Django 3.0.4 on 2020-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_pollingtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('option', models.CharField(default='', max_length=30)),
                ('vote', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pollingoption',
        ),
        migrations.DeleteModel(
            name='Pollingtitle',
        ),
    ]
